controller:
  use_worker: false
  subscribe_state: true
  subscribe_actuator_readings: true

controller_manager:
  failproof_controller: "SmbFailproofController"
  controller_pairs:
    - controller_pair:
        controller:
          plugin_name:              "SmbJoystickControllerPlugin"
          name:                     "SmbJoystickController"
          is_ros:                   true
          parameter_package:        "smb_joystick_controller"
          parameter_path:           "config/params.yaml"
        emergency_controller:
          plugin_name:              "SmbEmergencyControllerPlugin"
          name:                     "SmbEmergencyController"
          is_ros:                   false
          parameter_package:        "smb_emergency_controller"
          parameter_path:           ""
    - controller_pair:
        controller:
          plugin_name:              "SmbPathFollowingControllerPlugin"
          name:                     "SmbPathFollowingController"
          is_ros:                   true
          parameter_package:        "smb_path_following_controller"
          parameter_path:           "config/params.yaml"
        emergency_controller:
          plugin_name:              "SmbEmergencyControllerPlugin"
          name:                     "SmbEmergencyController"
          is_ros:                   false
          parameter_package:        "smb_emergency_controller"
          parameter_path:           ""