# Config file for Joy Manager
#############################

# Joysticks that are in use. Priority has to differ for all of them:
joysticks:
  - name: rqt
    topic: /anyjoy/rqt
    priority: 1
  - name: operator
    topic: /anyjoy/operator
    priority: 2

# Output publishers that are in use.
outputs:
  - name: joy_output
    topic: joy_throttle # add queue size and latch?
    type: Joy
    is_publishing: true
  - name: twist_output
    topic: commands/twist
    type: Twist
    is_publishing: true
  - name: pose_output
    topic: commands/pose
    type: Pose
    is_publishing: false  

# Timer: Seconds that pass before the priority is reset for all incomming messages
timer: 5.0

# Timeout: Seconds that pass before the last received message is no longer repeated
timeout: 10.0

# Timestep: Any_node time step inbetween calls to update(const any_worker::WorkerEvent& event)
time_step: 0.1

standalone: true

subscribers:
  twist_min:
    topic: /twist_min
    queue_size: 10
  twist_max:
    topic: /twist_max
    queue_size: 10
  pose_min:
    topic: /pose_min
    queue_size: 10
  pose_max:
    topic: /pose_max
    queue_size: 10
 
publishers:
  soft_emergency:
    topic: /soft_emcy_stop
    queue_size: 10
    latch: false
  hard_emergency:
    topic: /hard_emcy_stop
    queue_size: 10
    latch: false
  commands:
    pose:
      topic: command_pose
      queue_size: 1
      latch: false
    twist:
      topic: /anypulator_highlevel_controller/joy_cmd_vel
      queue_size: 1
      latch: false

notification:
  notifiers:
    default:
      topic: /notification
      queue_size: 100
      latch: false
      output_devices: 
        - "onboard_screen"
        - "joystick_screen"
        - "operator_screen"
    
# Default values for the mapping
# of joystick axes [-1,1] to 
# twist [twistMin, twistMax] and 
# pose [poseMin, poseMax]:
twist_output:
  twistMin:
    linear:
      x: -0.60
      y: -0.60
      z: -0.60
    angular:
      x: -1.5
      y: -1.5
      z: -1.5
  twistMax:
    linear:
      x: 0.60
      y: 0.60
      z: 0.60
    angular:
      x: 1.5
      y: 1.5
      z: 1.5

pose_output:
  poseMin:
    position:
      x: -1.0
      y: -1.0
      z: -1.0
    orientation:
      x: -0.462
      y: -0.191
      z: -0.462
      w: 0.733
  poseMax:
    position:
      x: 1.0
      y: 1.0
      z: 1.0
    orientation:
      x: 0.191
      y: 0.462
      z: 0.191
      w: 0.845
